# Generated by Django 4.1.5 on 2023-01-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('E_id', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('dept', models.CharField(max_length=100)),
            ],
        ),
    ]
